
security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern:      .*
            form_login:
                provider:       fos_userbundle
                login_path:     /myapp/login
                use_forward:    false
                check_path:     /myapp/login_check
                failure_path:   null
                default_target_path: /myapp
            logout:
                path:   /myapp/logout
                target: /myapp
            anonymous:    true